# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Blend.create(name: 'Dirty Hippie Blend', use_case: 'chill');
Blend.create(name: 'Envision Sleep', use_case: 'sleep');



# oils (blends)
  Oil.create(name: "3 Wise Men", use_cases: ["reverence", "spiritual awareness"]);
  Oil.create(name: "Abundance", use_cases: ["joy", "peace", "prosperity"]);
  Oil.create(name: "Acceptance", use_cases: ["self-worth"]);
  Oil.create(name: "AromaEase", use_cases: ["calming"]);
  Oil.create(name: "Aroma Life", use_cases: ["energizing", "sense of connection"]);
  Oil.create(name: "Aroma Siez", use_cases: ["soothing", "relaxing"]);
  Oil.create(name: "Australian Blue", use_cases: ["uplifting"]);
  Oil.create(name: "Awaken", use_cases: ["self aware", "positivity"]);
  Oil.create(name: "Believe", use_cases: ["strength", "faith"]);
  Oil.create(name: "Brain Power", use_cases: ["relaxing"]);
  Oil.create(name: "Build Your Dream", use_cases: ["empowering", "clarifying"]);
  Oil.create(name: "Christmas Spirit", use_cases: ["positive energy"]);
  Oil.create(name: "Citrus Fresh", use_cases: ["inspiring"]);
  Oil.create(name: "Clarity", use_cases: ["clarifying", "alertness"]);
  Oil.create(name: "Common Sense", use_cases: ["clarifying"]);
  Oil.create(name: "Cool Azul", use_cases: ["cooling"]);
  Oil.create(name: "Digize", use_cases: ["calming"]);
  Oil.create(name: "Dragon Time", use_cases: ["calming"]);
  Oil.create(name: "Dream Catcher", use_cases: ["positivity", "fulfillment"]);
  Oil.create(name: "Egyptian Gold", use_cases: ["devotion", "reverence"]);
  Oil.create(name: "En-r-gee", use_cases: ["uplifting", "energizing"]);
  Oil.create(name: "Endoflex", use_cases: ["calming", "balancing"]);
  Oil.create(name: "Envision", use_cases: ["creativity", "resourcefulness", "encouraging"]);
  Oil.create(name: "Exodus II", use_cases: ["divinity"]);
  Oil.create(name: "Forgiveness", use_cases: ["forgiveness"]);
  Oil.create(name: "Fulfill Your Destiny", use_cases: ["inspiring", "focusing"]);
  Oil.create(name: "Gathering", use_cases: ["inviting", "focusing"]);
  Oil.create(name: "Gentle Baby", use_cases: ["calming"]);
  Oil.create(name: "Glf", use_cases: ["wellness"]);
  Oil.create(name: "Gratitude", use_cases: ["gratefulness", "spiritual progress", "uplifting"]);
  Oil.create(name: "Grounding", use_cases: ["balancing", "clarity", "spirituality"]);
  Oil.create(name: "Harmony", use_cases: ["uplifting"]);
  Oil.create(name: "Highest Potential", use_cases: ["uplifting", "inspiring"]);
  Oil.create(name: "Hope", use_cases: ["faithfulness", "strength", "stability"]);
  Oil.create(name: "Humility", use_cases: ["spirituality"]);
  Oil.create(name: "Immupower", use_cases: ["positivity"]);
  Oil.create(name: "Inner Child", use_cases: ["connection", "inner self"]);
  Oil.create(name: "Inspiration", use_cases: ["spirituality", "meditation"]);
  Oil.create(name: "Into the Future", use_cases: ["invigorating"]);
  Oil.create(name: "Joy", use_cases: ["romantic", "warming", "blissfulness"]);
  Oil.create(name: "Juvacleanse", use_cases: ["wellness"]);
  Oil.create(name: "Juvaflex", use_cases: ["uplifting", "harmonizing"]);
  Oil.create(name: "Lady Sclareol", use_cases: ["relaxing"]);
  Oil.create(name: "Light the Fire", use_cases: ["empowering"]);
  Oil.create(name: "Live with Passion", use_cases: ["optimism", "enthusiam"]);
  Oil.create(name: "Live Your Passion", use_cases: ["focusing"]);
  Oil.create(name: "Logevity", use_cases: ["balancing"]);
  Oil.create(name: "M-Grain", use_cases: ["balancing", "calming"]);
  Oil.create(name: "Magnify Your Purpose", use_cases: ["creativity", "desire", "focusing", "motivating"]);
  Oil.create(name: "Melrose", use_cases: ["cleansing"]);
  Oil.create(name: "Mister", use_cases: ["empowering"]);
  Oil.create(name: "Motivation", use_cases: ["action", "accomplishment"]);
  Oil.create(name: "Oola Balance", use_cases: ["centering"]);
  Oil.create(name: "Oola Faith", use_cases: ["spirituality", "connectedness"]);
  Oil.create(name: "Oola Family", use_cases: ["love", "patience", "respect", "uplifting", "calming"]);
  Oil.create(name: "Oola Field", use_cases: ["strength", "clarifying"]);
  Oil.create(name: "Oola Finance", use_cases: ["positivity", "well-being", "clarity"]);
  Oil.create(name: "Oola Fitness", use_cases: ["uplifting", "energizing", "inspiring"]);
  Oil.create(name: "Oola Friends", use_cases: ["balancing", "empowerment", "confidence", "clarity"]);
  Oil.create(name: "Oola Fun", use_cases: ["uplifting", "revitalizing"]);
  Oil.create(name: "Oola Grow", use_cases: ["courage", "advancement"]);
  Oil.create(name: "Panway", use_cases: ["courage", "advancement"]);
  Oil.create(name: "Peace & Calming", use_cases: ["soothing", "relaxing"]);
  Oil.create(name: "Peace & Calming II", use_cases: ["relaxing"]);
  Oil.create(name: "Present Time", use_cases: ["focus"]);
  Oil.create(name: "Purification", use_cases: ["cleansing"]);
  Oil.create(name: "R.C.", use_cases: ["motivating", "invigorating"]);
  Oil.create(name: "Raven", use_cases: ["cooling"]);
  Oil.create(name: "Release", use_cases: ["relaxing", "harmony", "balance"]);
  Oil.create(name: "Relieve It", use_cases: ["comforting", "soothing"]);
  Oil.create(name: "Rutayala", use_cases: ["relaxing"]);
  Oil.create(name: "Sacred Mountain", use_cases: ["strength", "empowerment", "grounding", "protection"]);
  Oil.create(name: "Sara", use_cases: ["soothing"]);
  Oil.create(name: "Sclaressence", use_cases: ["wellness"]);
  Oil.create(name: "Sensation", use_cases: ["love", "affection"]);
  Oil.create(name: "Stress Away", use_cases: ["relaxing", "comforting"]);
  Oil.create(name: "Surrender", use_cases: ["calmness", "worry-free"]);
  Oil.create(name: "The Gift", use_cases: ["energizing"]);
  Oil.create(name: "Thieves", use_cases: ["wellness"]);
  Oil.create(name: "AromaEase", use_cases: ["calming"]);
  Oil.create(name: "Transformation", use_cases: ["empowering", "uplifting"]);
  Oil.create(name: "Trauma Life", use_cases: ["support"]);
  Oil.create(name: "Valor", use_cases: ["empowering", "balancing"]);
  Oil.create(name: "White Angelica", use_cases: ["protection", "security", "positive energy"]);

#oils (singles)
Oil.create(name: "Angelica", use_cases: ["soothing", "relaxing"]);
Oil.create(name: "Basil", use_cases: ["calming", "refreshing"]);
Oil.create(name: "Bergamot", use_cases: ["uplifting", "relaxing"]);
Oil.create(name: "Black Pepper", use_cases: ["energizing"]);
Oil.create(name: "Blue Cypress", use_cases: ["calming", "soothing"]);
Oil.create(name: "Blue Tansy", use_cases: ["uplifting"]);
Oil.create(name: "Cardamom", use_cases: ["refreshing"]);
Oil.create(name: "Carrot Seed", use_cases: ["soothing", "grounding"]);
Oil.create(name: "Cedarwood", use_cases: ["calming", "comforting"]);
Oil.create(name: "Cinnamon Bark", use_cases: ["abundance", "inviting"]);
Oil.create(name: "Cistus", use_cases: ["soothing", "uplifting"]);
Oil.create(name: "Citronella", use_cases: ["refreshing"]);
Oil.create(name: "Clary Sage", use_cases: ["calming", "relaxing"]);
Oil.create(name: "Clove", use_cases: ["warming", "inviting"]);
Oil.create(name: "Copaiba", use_cases: ["soothing"]);
Oil.create(name: "Coriander", use_cases: ["calming", "uplifting"]);
Oil.create(name: "Cypress", use_cases: ["security", "grounding"]);
Oil.create(name: "Dill", use_cases: ["calming"]);
Oil.create(name: "Dorado Azul", use_cases: ["comforting", "relaxing", "settling"]);
Oil.create(name: "Elemi", use_cases: ["clarity", "mood-boosting"]);
Oil.create(name: "Eucalyptus Blue", use_cases: ["calming", "invigorating"]);
Oil.create(name: "Eucalyptus Globulus", use_cases: ["stimulating"]);
Oil.create(name: "Eucalyptus Radiata", use_cases: ["stimulating", "rejuvenating"]);
Oil.create(name: "Fennel", use_cases: ["grounding"]);
Oil.create(name: "Frankincense", use_cases: ["grounding", "purpose"]);
Oil.create(name: "Geranium", use_cases: ["peaceful", "spiritual"]);
Oil.create(name: "German Chamomile", use_cases: ["peaceful", "patience"]);
Oil.create(name: "Ginger", use_cases: ["energizing"]);
Oil.create(name: "Goldenrod", use_cases: ["calming", "relaxing"]);
Oil.create(name: "Grapefruit", use_cases: ["uplifting"]);
Oil.create(name: "Helichrysum", use_cases: ["stimulating"]);
Oil.create(name: "Hinoki", use_cases: ["spiritual"]);
Oil.create(name: "Hong Kuai", use_cases: ["uplifting", "spiritual", "clarity", "intuition", "action"]);
Oil.create(name: "Hyssop", use_cases: ["creativity", "meditation"]);
Oil.create(name: "Idaho Balsam Fir", use_cases: ["grounding", "calming"]);
Oil.create(name: "Idaho Blue Spruce", use_cases: ["pleasing", "relaxing"]);
Oil.create(name: "Jade Lemon", use_cases: ["pleasing", "uplifting", "inviting"]);
Oil.create(name: "Jasmine", use_cases: ["relaxing", "self-confidence"]);
Oil.create(name: "Juniper", use_cases: ["peaceful"]);
Oil.create(name: "Kunzea", use_cases: ["purifying"]);
Oil.create(name: "Lavender", use_cases: ["calming", "soothing"]);
Oil.create(name: "Ledum", use_cases: ["meditation"]);
Oil.create(name: "Lemon", use_cases: ["refreshing"]);
Oil.create(name: "Lemon Myrtle", use_cases: ["uplifting", "refreshing"]);
Oil.create(name: "Lemongrass", use_cases: ["balancing", "refreshing", "relaxing"]);
Oil.create(name: "Lime", use_cases: ["positive feelings", "light", "uplifting"]);
Oil.create(name: "Manuka", use_cases: ["relaxing"]);
Oil.create(name: "Marjoram", use_cases: ["relaxing", "calming"]);
Oil.create(name: "Mastrante", use_cases: ["calming", "relaxing"]);
Oil.create(name: "Melaleuca Quinquenervia", use_cases: []);
Oil.create(name: "Melissa", use_cases: ["pleasant", "uplifting", "encouraging"]);
Oil.create(name: "Mountain Savory", use_cases: ["energizing", "support"]);
Oil.create(name: "Myrrh", use_cases: ["spirituality", "invigorating"]);
Oil.create(name: "Neroli", use_cases: ["uplifting"]);
Oil.create(name: "Northern Lights Black Spruce", use_cases: ["meditation", "refreshing"]);
Oil.create(name: "Nutmeg", use_cases: ["energizing", "uplifting"]);
Oil.create(name: "Orange", use_cases: ["calming", "inspiring"]);
Oil.create(name: "Oregano", use_cases: ["wellness", "invigorating"]);
Oil.create(name: "Palmarosa", use_cases: ["stimulating", "soothing"]);
Oil.create(name: "Palo Santo", use_cases: ["cleansing", "refreshing", "inspiring"]);
Oil.create(name: "Patchouli", use_cases: ["calming", "relaxing", "peaceful"]);
Oil.create(name: "Peppermint", use_cases: ["peaceful"]);
Oil.create(name: "Petitgrain", use_cases: ["uplifting", "refreshing"]);
Oil.create(name: "Pine", use_cases: ["calming"]);
Oil.create(name: "Ravintsara", use_cases: ["meditation"]);
Oil.create(name: "Roman Chamomile", use_cases: ["calming"]);
Oil.create(name: "Rose", use_cases: ["positivity", "self-reflection"]);
Oil.create(name: "Rosemary", use_cases: ["clarity"]);
Oil.create(name: "Royal Hawaiian Sandalwood", use_cases: []);
Oil.create(name: "Sacred Frankincense", use_cases: ["spiritual", "meditation"]);
Oil.create(name: "Sacred Sandalwood", use_cases: ["uplifting"]);
Oil.create(name: "Sage", use_cases: ["clarifying", "uplifting"]);
Oil.create(name: "Spearmint", use_cases: ["invigorating", "uplifting", "calming"]);
Oil.create(name: "Tangerine", use_cases: ["stimulating", ]);
Oil.create(name: "Tea Tree", use_cases: ["purifying"]);
Oil.create(name: "Thyme", use_cases: ["purposeful"]);
Oil.create(name: "Tsuga", use_cases: ["spiritual", "uplifting"]);
Oil.create(name: "Valerian", use_cases: ["calming", "grounding"]);
Oil.create(name: "Vetiver", use_cases: ["grounding", "calming", "relaxing"]);
Oil.create(name: "Wintergreen", use_cases: ["stimulating", "invigorating"]);
Oil.create(name: "Xiang Mao", use_cases: ["enlightening"]);
Oil.create(name: "Ylang Ylang", use_cases: ["romantic", "relaxing"]);
